// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Verify environment variables
if (!SUPABASE_URL) {
  console.error('VITE_SUPABASE_URL is not defined');
  throw new Error('Supabase URL configuration is missing');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('VITE_SUPABASE_PUBLISHABLE_KEY is not defined');
  throw new Error('Supabase key configuration is missing');
}

// Initialize Supabase with auth configuration
const supabaseUrl = SUPABASE_URL.trim();
const supabaseKey = SUPABASE_PUBLISHABLE_KEY.trim();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Runtime debug: print a masked version of the publishable key so you can confirm
// the client loaded the correct env var. This is safe: we print only the first
// and last 4 chars. Remove this in production.
try {
  const _key = SUPABASE_PUBLISHABLE_KEY?.toString() ?? '';
  if (typeof window !== 'undefined') {
    const masked = _key ? `${_key.slice(0,4)}...${_key.slice(-4)}` : 'MISSING';
    // eslint-disable-next-line no-console
    console.debug('[supabase] publishable key:', masked);
  }
} catch (e) {
  // ignore
}

// Keep localStorage 'token' in sync with Supabase session so backend requests
// that rely on localStorage('token') (axios interceptors) work.
if (typeof window !== 'undefined') {
  // on startup, populate token if session exists
  supabase.auth.getSession().then(({ data: { session } }) => {
    const token = (session as any)?.access_token ?? null;
    if (token) localStorage.setItem('token', token);
  }).catch(() => {});

  // listen for auth state changes and update token accordingly
  supabase.auth.onAuthStateChange((_event, session) => {
    const token = (session as any)?.access_token ?? null;
    if (token) localStorage.setItem('token', token);
    else localStorage.removeItem('token');
  });
}