// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer build-time inlined VITE_* values, but fall back to a runtime-injected
// configuration (window.__ENV__) when the bundle was built without VITE vars.
const RUNTIME_ENV = typeof window !== 'undefined' ? (window as any).__ENV__ || {} : {};
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || RUNTIME_ENV.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || RUNTIME_ENV.VITE_SUPABASE_PUBLISHABLE_KEY;

// Verify environment variables
if (!SUPABASE_URL) {
  console.error('VITE_SUPABASE_URL is not defined');
  throw new Error('Supabase URL configuration is missing');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('VITE_SUPABASE_PUBLISHABLE_KEY is not defined');
  throw new Error('Supabase key configuration is missing');
}

// Initialize Supabase with auth configuration
const supabaseUrl = SUPABASE_URL.trim();
const supabaseKey = SUPABASE_PUBLISHABLE_KEY.trim();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  // Do NOT persist session to browser storage. We prefer keeping auth
  // sessions in-memory and using explicit retrieval (supabase.auth.getSession())
  // for backend calls. This prevents the browser from storing tokens in
  // localStorage and satisfies the requirement that "the browser should
  // not store anything".
  auth: {
    persistSession: false,
    autoRefreshToken: false,
  }
});

// Expose the supabase client to the browser console in development only so
// you can run `await __supabase.auth.getSession()` from DevTools for debugging.
// This will not run in production builds.
try {
  if (typeof window !== 'undefined' && (import.meta as any).env?.DEV) {
    (window as any).__supabase = supabase;
  }
} catch (e) {
  // ignore in environments where import.meta.env isn't accessible
}

// Runtime debug: print a masked version of the publishable key so you can confirm
// the client loaded the correct env var. This is safe: we print only the first
// and last 4 chars. Remove this in production.
try {
  const _key = SUPABASE_PUBLISHABLE_KEY?.toString() ?? '';
  if (typeof window !== 'undefined') {
    const masked = _key ? `${_key.slice(0,4)}...${_key.slice(-4)}` : 'MISSING';
    // eslint-disable-next-line no-console
    console.debug('[supabase] publishable key:', masked);
  }
} catch (e) {
  // ignore
}

// We intentionally avoid syncing tokens into localStorage here.
// Any parts of the app that need a token for server requests should
// call `supabase.auth.getSession()` at request time (see blog.service.ts
// interceptor changes) so tokens are never persisted to browser storage.